### ISSUE TITLE
[Feature] The machine configuration depends on config.yaml(.dist) file

### ISSUE THREAD

**Issue by xuanquynh** [xuanquynh/local-virtual-servers#1]
**Description**  
Add two files called config.yaml.dist and config.yaml that allow developers to easily customize machine configuration.

**Example**  
```yaml
version: "1.0"

stack:
  apache: 2.4
  php: 7.3
  mysql: 5.7

memory: 1024
```
